### ISSUE TITLE
Provide pinata PeerIDs for folks to connect to

### ISSUE THREAD

**Issue by olizilla** [PinataCloud/Pinata-SDK#5]
The `pinHashToPinata` allows the user to provide their multiaddr to connect to to speed up the content discovery. That's a nice touch, but for the use-case where you are on a network where you can't forward a port on the public IP, it might work better to provide the multiaddrs of the pinata nodes, so folks could connect to you directly, rather than ask you to try and connect to them.

It'd also be rad to support `/p2p-circuit` multiaddrs in the current api, so connections could be relayed to NAT'd nodes via relays. I think there are bunch of relay nodes in the network now.

- https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#circuit-relay
- https://github.com/ipfs/js-ipfs/tree/master/examples/circuit-relaying

**Comment by silasdavis** [comment]
This feels like a major omission. I was surprised to not be able to find your actual peer addresses and IDs on your own website.

Some purported nodes are listed here: https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list but it seems there are no A records on those subdomains anyway.

I've found that trying to pull content pinned on pinata through a local node typically just hangs for hours so it seems like it is essential to peer with your nodes in order to access files pinned in a timely manner. Obviously I could just pull from your gateway, but that kind of misses the point...
